import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import Layout from '@/components/Layout/Layout';

const Home: NextPageWithLayout = () => {
  return (
    <Layout>
      <Head>
        <title>Multi_Vendor E-Commerce Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container main__app'>
        <p>Welcome to web application</p>
      </main>
    </Layout>
  )
}


export default Home;
